### ISSUE TITLE
Delete By Row ID Not Working

### ISSUE THREAD

**Issue by darrylackley** [xmunoz/sodapy#81] opened 2021-05-25 20:27 UTC
I'm trying to delete individual rows by `row_id` using the following:

```
client.delete("data-set", row_id=2)
```

where but am getting the following result

```
HTTPError: 400 Client Error: Bad Request.
	Column is maltyped; for field ':id' we expected 'row_identifier' but got '"2"'
```

I don't have an explicit Row Identifier on the table.  Unfortunately it's a private data set as its in a Tyler instantiation for criminal justice data, so I can't share the URL for reproduction.  I've verified that `delete` works (removes the entire table), so I don't think it's a permission issue.  Any help is appreciated.

**Comment by xmunoz** [comment] 2021-05-25 21:59
Are you able to manually execute an HTTP `DELETE` request with curl or something similar? According to [this doc](https://dev.socrata.com/docs/row-identifiers.html#retrieving-rows-by-their-identifiers), the URL structure for datasets with publisher-specified identifiers should be the same, but clearly this isn't working for you.

If you manage to figure it out, please post the full successful HTTP request or curl command here so that I can update the library to work for this use case.

**Comment by xmunoz** [comment] 2021-07-23 14:27
Since there is no repro for this bug, I'm going to close this. Feel free to re-open once you have the steps to reproduce or at least a successful curl request.

**Closed by xmunoz** 2021-07-23 14:27 UTC
